# Generated by Django 5.0.6 on 2024-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('body', models.CharField(max_length=25, verbose_name='Body')),
                ('createdBy', models.CharField(blank=True, default='admin', max_length=25, verbose_name='Created By')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
            ],
        ),
    ]
