# Generated by Django 5.0.6 on 2024-12-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='disliked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
