# Generated by Django 5.0.6 on 2024-12-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_comments_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subComments',
            field=models.ManyToManyField(blank=True, to='posts.comment'),
        ),
    ]
