# Generated by Django 5.0.6 on 2024-12-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_createdby'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
